- name: detail esxi configuration
  community.vmware.vmware_host_config_manager:
    hostname: "{{ esxi_host }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_pass }}"
    esxi_hostname: "{{ esxi_host }}"
    options:
      Syslog.global.logDir: '[my-iscsi] VMHost-Log'
      Syslog.global.logDirUnique: true
    validate_certs: False
  delegate_to: localhost